services:
  mongodb:
    image: mongo:latest
    container_name: visor_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - ./mongo-data:/data/db

